using Amazon.CDK;
using Amazon.CDK.AWS.AppConfig;
using Amazon.CDK.AWS.EC2;
using Amazon.CDK.AWS.ECS;
using Amazon.CDK.AWS.ECS.Patterns;
using Amazon.CDK.AWS.RDS;
using Amazon.CDK.AWS.SSM;
using Constructs;

namespace Account.Cdk;

/// <summary>
/// Infrastructure for the Accounts microservice.
///
///   - VPC with public/private subnets.
///   - RDS PostgreSQL with credentials generated into Secrets Manager
///     (no secrets in code/config, per S1 spec).
///   - ECS Fargate service behind an Application Load Balancer, image built
///     from the service Dockerfile.
///   - SSM Parameter Store entries for non-secret config.
///   - AWS AppConfig application/environment/profile for feature flags.
/// </summary>
public sealed class AccountServiceStack : Stack
{
    internal AccountServiceStack(Construct scope, string id, IStackProps props)
        : base(scope, id, props)
    {
        var vpc = new Vpc(this, "AccountVpc", new VpcProps
        {
            MaxAzs = 2,
            NatGateways = 1
        });

        // --- RDS PostgreSQL ---
        // Credentials are generated by CDK and stored in Secrets Manager.
        var dbCredentials = Credentials.FromGeneratedSecret("accounts_admin", new CredentialsBaseOptions
        {
            SecretName = "account-service/db-credentials"
        });

        var database = new DatabaseInstance(this, "AccountDb", new DatabaseInstanceProps
        {
            Engine = DatabaseInstanceEngine.Postgres(new PostgresInstanceEngineProps
            {
                Version = PostgresEngineVersion.VER_16
            }),
            Vpc = vpc,
            VpcSubnets = new SubnetSelection { SubnetType = SubnetType.PRIVATE_WITH_EGRESS },
            InstanceType = Amazon.CDK.AWS.EC2.InstanceType.Of(InstanceClass.BURSTABLE3, InstanceSize.MICRO),
            Credentials = dbCredentials,
            DatabaseName = "accounts",
            AllocatedStorage = 20,
            MaxAllocatedStorage = 100,
            MultiAz = false,
            RemovalPolicy = RemovalPolicy.SNAPSHOT,
            DeletionProtection = true,
            StorageEncrypted = true
        });

        // --- ECS Fargate service ---
        var cluster = new Cluster(this, "AccountCluster", new ClusterProps
        {
            Vpc = vpc,
            ContainerInsightsV2 = ContainerInsights.ENABLED
        });

        var fargate = new ApplicationLoadBalancedFargateService(this, "AccountFargate",
            new ApplicationLoadBalancedFargateServiceProps
            {
                Cluster = cluster,
                Cpu = 256,
                MemoryLimitMiB = 512,
                DesiredCount = 2,
                PublicLoadBalancer = true,
                TaskImageOptions = new ApplicationLoadBalancedTaskImageOptions
                {
                    // Builds the service image from the repo Dockerfile at deploy time.
                    Image = ContainerImage.FromAsset(".."),
                    ContainerPort = 8080,
                    Environment = new System.Collections.Generic.Dictionary<string, string>
                    {
                        ["ASPNETCORE_URLS"] = "http://+:8080",
                        ["ASPNETCORE_ENVIRONMENT"] = "Production"
                    },
                    // Inject DB credentials as secrets (never plaintext env/config).
                    Secrets = new System.Collections.Generic.Dictionary<string, Amazon.CDK.AWS.ECS.Secret>
                    {
                        ["ConnectionStrings__AccountsDb"] =
                            Amazon.CDK.AWS.ECS.Secret.FromSecretsManager(database.Secret!)
                    }
                }
            });

        // Allow the Fargate tasks to reach the database.
        database.Connections.AllowDefaultPortFrom(fargate.Service);

        fargate.TargetGroup.ConfigureHealthCheck(new Amazon.CDK.AWS.ElasticLoadBalancingV2.HealthCheck
        {
            Path = "/health",
            HealthyHttpCodes = "200"
        });

        // --- SSM Parameter Store (non-secret config) ---
        _ = new StringParameter(this, "OtelEndpointParam", new StringParameterProps
        {
            ParameterName = "/account-service/otel/exporter-endpoint",
            StringValue = "http://otel-collector.account.svc.cluster.local:4317",
            Description = "OTLP exporter endpoint for OpenTelemetry."
        });

        // --- AWS AppConfig (feature flags) ---
        var appConfigApp = new CfnApplication(this, "AccountAppConfig", new CfnApplicationProps
        {
            Name = "account-service"
        });

        var appConfigEnv = new CfnEnvironment(this, "AccountAppConfigEnv", new CfnEnvironmentProps
        {
            ApplicationId = appConfigApp.Ref,
            Name = "production"
        });

        _ = new CfnConfigurationProfile(this, "AccountFeatureFlags", new CfnConfigurationProfileProps
        {
            ApplicationId = appConfigApp.Ref,
            Name = "feature-flags",
            LocationUri = "hosted",
            Type = "AWS.AppConfig.FeatureFlags"
        });

        // --- Outputs ---
        _ = new CfnOutput(this, "LoadBalancerDns", new CfnOutputProps
        {
            Value = fargate.LoadBalancer.LoadBalancerDnsName,
            Description = "Public DNS of the Accounts service load balancer."
        });

        _ = new CfnOutput(this, "DbSecretArn", new CfnOutputProps
        {
            Value = database.Secret!.SecretArn,
            Description = "Secrets Manager ARN holding the database credentials."
        });

        _ = new CfnOutput(this, "AppConfigApplicationId", new CfnOutputProps
        {
            Value = appConfigApp.Ref,
            Description = "AppConfig application id used for feature flags."
        });
    }
}
